### ISSUE TITLE
feat: Angular 10 support

### ISSUE THREAD

**Issue by hatsantos** [ionic-team/angular-toolkit#248]
# Feature Request
Update Ionic framework to support Angular 10 and typescript 3.9.

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
The new version of Angular came out (Angular 10).
Update Ionic Angular dependencies to support the new version of Angular.
Angular 10 also pushes Typescript to version 3.9.

**Describe Preferred Solution**
Update Ionic Angular dependencies to support the new version of Angular.

**Additional Context**
Blog post about release: https://blog.angular.io/version-10-of-angular-now-available-78960babd41
Change Log v10: https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by liamdebeasi** [comment]
For context, Angular removed some code in the latest version of `@schematics/angular` that is causing `@ionic/angular-toolkit` to break when using a component generator.

Affected code:

https://github.com/ionic-team/angular-toolkit/blob/9f279e13b861143bcdd1c92cf23a0239e851d98b/schematics/component/index.ts#L5
https://github.com/ionic-team/angular-toolkit/blob/9f279e13b861143bcdd1c92cf23a0239e851d98b/schematics/page/index.ts#L5


Here is the PR that removed the code on Angular's side: https://github.com/angular/angular-cli/pull/17597

One thought is to maybe move to using the `getWorkspace` function and query the result for the user's project.

**Comment by KevinKelchen** [comment]
FWIW, while I haven't had an issue with Ionic on Angular 10, I did see the [Angular Update Guide](https://update.angular.io/#9.1:10.0l3) say, "Stop using `styleext` or `spec` in your Angular schematics. `ng update` will migrate you automatically."

For us, `ng update` made no changes although the `angular.json` has the following:

```json
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    }
  }
```

Not sure if that Angular CLI migration is targeted towards schematic authors or end users.

Using the Ionic CLI I'm able to successfully generate Pages and Components including their `.scss` files.

**Comment by bondseid** [comment]
> I did have an issue using the latest angular, ionic, and ionic-cli. I'm not certain if this is an issue that should be in the `ionic-cli` project or not as it appears to have to do with ionic's usage of angular schematics (let me know if this should become an issue in another repo):
> 
> ```shell
> $ ionic g page home
> > ng generate page home --project=app
> An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
> Require stack:
> - /redacted/path/to/app/node_modules/@ionic/angular-toolkit/schematics/page/index.js
> - /redacted/path/to/app/node_modules/@angular-devkit/schematics/tools/export-ref.js
> - /redacted/path/to/app/node_modules/@angular-devkit/schematics/tools/index.js
> - /redacted/path/to/app/node_modules/@angular/cli/utilities/json-schema.js
> - /redacted/path/to/app/node_modules/@angular/cli/models/command-runner.js
> - /redacted/path/to/app/node_modules/@angular/cli/lib/cli/index.js
> - /redacted/path/to/app/node_modules/@angular/cli/lib/init.js
> - /redacted/path/to/app/node_modules/@angular/cli/bin/ng
> See "/tmp/ng-8qbJHz/angular-errors.log" for further details.
> [ERROR] Could not generate page.
> ```
> 
> And here's the output of `ionic info`:
> 
> ```shell
> Ionic:
> 
>    Ionic CLI                     : 6.10.1 (/redacted/path/to/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 5.2.2
>    @angular-devkit/build-angular : 0.1000.0
>    @angular-devkit/schematics    : 10.0.0
>    @angular/cli                  : 10.0.0
>    @ionic/angular-toolkit        : 2.2.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : not available
>    Cordova Plugins   : not available
> 
> Utility:
> 
>    cordova-res : 0.15.1
>    native-run  : 1.0.0
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/redacted/path/to/.android/sdk)
>    NodeJS            : v12.18.1 (/usr/bin/node)
>    npm               : 6.14.5
>    OS                : Linux 5.4
> ```

I am facing the same issue after upgrading from ionic 4 and angular 8.

**Comment by oneclickwebstudio** [comment]
Hello!

Catching error while running command `ng g component example`

# 🐞 Bug report

### Command (mark with an `x`)



- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc


### Is this a regression?


 Yes, the previous version in which this bug was not present was: Working well


## 🔬 Minimal Reproduction

 
After updating to `"@schematics/angular": "^10.0.3"`  command `ng g component example` breaks
in `"@schematics/angular": "^9.1.11"` everything is OK.


## 🔥 Exception or Error
<pre><code>An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
Require stack:
- .../node_modules/@ionic/angular-toolkit/schematics/component/index.js
- .../node_modules/@angular-devkit/schematics/tools/export-ref.js
- .../node_modules/@angular-devkit/schematics/tools/index.js
- .../node_modules/@angular/cli/utilities/json-schema.js
- .../node_modules/@angular/cli/models/command-runner.js
- .../node_modules/@angular/cli/lib/cli/index.js
- .../.npm-global/lib/node_modules/@angular/cli/lib/init.js
- .../.npm-global/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/2k/vlq4_8v57_98l_9rvxwmj1km0000gn/T/ng-aqdfcZ/angular-errors.log" for further details.
</code></pre>


## 🌍 Your Environment
<pre><code>Angular CLI: 10.0.3
Node: 12.16.3
OS: darwin x64

Angular: 10.0.4
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1000.3 (cli-only)
@angular-devkit/build-angular   0.1000.3
@angular-devkit/core            10.0.3
@angular-devkit/schematics      10.0.3
@angular/cli                    10.0.3
@schematics/angular             10.0.3
@schematics/update              0.1000.3 (cli-only)
rxjs                            6.6.0
typescript                      3.9.7


ionic -v
6.10.1
</code></pre>

**Anything else relevant?**
