### ISSUE TITLE
Invalid options object in Copy Plugin initialization

### ISSUE THREAD

**Issue by gRegorLove** [ionic-team/angular-toolkit#420]
**Description:**
Creating an Ionic 5, Angular project gives an error when trying to run `ionic serve`. Possible regression of #265 in v2.3.3?

**Steps to Reproduce:**
Create a new Ionic project with tabs template:
`ionic start events-alpha tabs --type=angular`

Run:
`ionic serve --devapp`

**Output:**
```
[ng] An unhandled exception occurred: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
[ng]  - options.patterns should be an non-empty array.

[ERROR] ng has unexpectedly closed (exit code 127).
```

Extended message from angular-errors.log:
```
[error] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be an non-empty array.
    at validate (\events-alpha\node_modules\schema-utils\dist\validate.js:98:11)
    at new CopyPlugin (\events-alpha\node_modules\copy-webpack-plugin\dist\index.js:24:30)
    at Object.webpackConfiguration (\events-alpha\node_modules\@ionic\angular-toolkit\builders\cordova-serve\index.js:52:39)
    at setup (\events-alpha\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:88:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Environment:**
```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

Edit: Added the `--devapp` in the ionic serve command

**Comment by mhartington** [comment]
Do you have a sample project to look at?

**Comment by gRegorLove** [comment]
@mhartington Sure, it's just the default created by ionic start: https://github.com/gRegorLove/example-ionic

**Comment by mhartington** [comment]
I will note the `--devapp` flag has long since been removed from the Ionic CLI as DevApp itself was shut down.

I'm not able to replicate it on my mac, so wondering if it's windows specific. 
Are you only seeing it with the old flag?

**Comment by gRegorLove** [comment]
I understand it's deprecated, but ionic cli 5.4 still supports it and DevApp has generally still been working. Unfortunately it's still needed in order to test on an iOS device.

**Comment by mhartington** [comment]
We've long since retired devapp and the accompanying CLI code to support it. 


As it stands, the tools you're using are no longer supported, so we won't be fixing this. 
Another option is to upgrade to Capacitor, which has better support for plugins/features in the browser so the development experience would no longer require testing on a real device. 

Going to close this.

**Comment by gRegorLove** [comment]
@mhartington I don't understand; is this not an issue with @ionic/angular-toolkit, independent of devapp?

**Comment by mhartington** [comment]
No, not fully, because the CLI flags that get passed from the `ionic` command to the angular builder are different.

With the v5.4.16 ionic CLI installed, the command will _actually_ call

```
> ng run app:ionic-cordova-serve --host=0.0.0.0 --port=8100 --cordova-mock --consolelogs --consolelogs-port=53703
```

Which at the time was the correct flags to be passed.
But since we retired devapp and removed the code for it from the cli, we no longer needed to use all those flags and were able to rewrite things.

Again it comes back to the **old* ionic cli being used and it passing out of date flags.

**Comment by rajatPhonegap** [comment]
I am facing the same issue. How can I used devApp for now ?

**Comment by mhartington** [comment]
DevApp functionality has been removed from the CLI as the app was shut down.
