### ISSUE TITLE
Error on latest @ionic/angular-toolkit dependencies

### ISSUE THREAD

**Issue by digoburigo** [ionic-team/angular-toolkit#462]
Angular Version
`"@angular/core": "~12.2.12",`
`"@angular/cli": "~12.2.12",`

Error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: webgeo-mobile@0.0.1
npm ERR! Found: @angular-devkit/architect@0.1202.12
npm ERR! node_modules/@angular-devkit/architect
npm ERR!   dev @angular-devkit/architect@"^0.1202.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/architect@"^0.1201.1" from @ionic/angular-toolkit@5.0.0
npm ERR! node_modules/@ionic/angular-toolkit
npm ERR!   dev @ionic/angular-toolkit@"^5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/digob/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/digob/.npm/_logs/2021-10-28T21_24_00_938Z-debug.log
```

**Comment by digoburigo** [comment]
I realized that the error occurs when the angular project has this dependencie `"@angular-devkit/architect": "^0.1202.12"` installed

**Comment by digoburigo** [comment]
I created a new Ionic project and compare the dependencies versions and `jasmine-core` in my project was in version `3.6.0` and in the new Ionic project was `3.8.0`. And this dependencie was blocking me for uninstalling the `@angular-devkit/architect` after updating the `jasmine-core` I was able remove `@angular-devkit/architect` and install the `@ionic/angular-toolkit@5.0.0`. I don't know if this was exactly the problem but it worked for me. 
Feel free to close this issue. Thanks for your time.

**Comment by RowTracker** [comment]
Please can you release a new build of @ionic/angular-devkit with all Angular dependencies updated to the latest release of Angular, currently 12.2.12.
The problem is caused by 5.0.0 having a dependency on Angular 12.1.1. This means if you install a version of Angular above 12.1.x, such as the current build 12.2.12. NPM will report nasty compatibility errors and fail. You can use the --force option on NPM for force the update but then this causes problems with using NPM AUDIT. 

 As stated by @mhartington in issue 437 this problem is appears to be caused by the semver numbering scheme used for @angular/devkit which causes npm to throw the compatibility errors. However, that does not help developers trying to install @ionic with the latest version of @Angular.  I am in the process of trying to upgrade to Ionic6RC1. This problem here is made worse because Ionic 6 forces a dependancy on rxjs 6.6.0 but Angular 12.1.1 uses rxjs 6.5.x. This means anyone who wants to use Ionic 6 with Angular has to accept that NPM AUDIT is broken until we get a new release of @ionic/angular-devkit.

In my opinion I think we need a new release of @ionic/angular-devkit with dependencies set to @angular@12.2.12 (0.1202.12 for the devkit). In the medium term Ionic needs to find a way to allow minor version upgrades of Angular devkit that do not cause NPM to report compatibility errors.

**Comment by mhartington** [comment]
@RowTracker the semver ranges used here do allow for minor/patch releases in angular's tools. The only package that does seem to be causing an issue is `@angular-devkit/architect` because it has an odd version range.

Bumping dep to match ever minor release is not feasible, hence the version range. I think a better option is to probably switch the peerDep to not require `@angular-devkit/architect` but `@angular-devkit/build-angular`.

**Comment by RowTracker** [comment]
That looks like great solution. I hope you can release it soon. I've spent most of today building from the Ionic blank starter project to Angular12 and Ionic6, trying to install each upgrade by the book. Just got it working using Cordova and running both on Android and IOS.

Sorry if this is an inappropriate place to ask but do you know what the trick is to build for IOS and Android in development mode. Angular has documented how they have made production mode the default but I can't find any documentation on how to get Ionic builds to happen in development mode.

**Comment by mhartington** [comment]
Ok, this should be taken care of as of `@ionic/angular-toolkit@5.0.1`
